"""Run script to perform a test run for the capacitated facility location problem.

Steps performed:
1) Load facility and customer data (JSON) generated by data/generate_sample_data.py
2) Build an initial greedy solution
3) Apply neighborhood moves and run Simulated Annealing
4) Print final solution
5) Save results to file (JSON)
6) Solve an exact MIP using PuLP to compare
7) Produce a PNG visualization of facilities and assignments

Requirements: numpy, pulp, matplotlib
"""
import argparse
import json
import math
import os
import random
from copy import deepcopy

try:
    import numpy as np
except Exception:
    np = None

try:
    import pulp
except Exception:
    pulp = None

try:
    import matplotlib.pyplot as plt
    import matplotlib.cm as cm
except Exception:
    plt = None
    cm = None


def load_data(path):
    with open(path) as f:
        data = json.load(f)
    facilities = data["facilities"]
    customers = data["customers"]
    return facilities, customers


def compute_distances(facilities, customers):
    m = len(facilities)
    n = len(customers)
    dist = [[0.0] * m for _ in range(n)]
    for i, c in enumerate(customers):
        for j, f in enumerate(facilities):
            dx = c["x"] - f["x"]
            dy = c["y"] - f["y"]
            dist[i][j] = math.hypot(dx, dy)
    return dist


def greedy_initial_solution(facilities, customers, dist):
    # Simple greedy: open facilities in increasing fixed_cost/capacity until all customers can be assigned
    m = len(facilities)
    n = len(customers)
    fac_order = sorted(range(m), key=lambda j: facilities[j]["fixed_cost"] / facilities[j]["capacity"])
    open_set = set()
    capacities = [0] * m
    assignment = [-1] * n

    def try_assign(open_set):
        caps = [facilities[j]["capacity"] for j in range(m)]
        assign = [-1] * n
        for i in sorted(range(n), key=lambda ii: customers[ii]["demand"], reverse=True):
            dem = customers[i]["demand"]
            # choose nearest open facility with enough capacity
            best = None
            best_d = float("inf")
            for j in open_set:
                if caps[j] >= dem and dist[i][j] < best_d:
                    best = j
                    best_d = dist[i][j]
            if best is None:
                return None
            assign[i] = best
            caps[best] -= dem
        return assign

    for j in fac_order:
        open_set.add(j)
        a = try_assign(open_set)
        if a is not None:
            assignment = a
            break
    # If still None (rare), open all facilities and force greedy assign ignoring capacity
    if assignment[0] == -1:
        open_set = set(range(m))
        caps = [facilities[j]["capacity"] for j in range(m)]
        for i in sorted(range(n), key=lambda ii: customers[ii]["demand"], reverse=True):
            dem = customers[i]["demand"]
            # choose nearest facility with capacity, if none, choose nearest and allow capacity to go negative
            best = min(range(m), key=lambda j: dist[i][j])
            assignment[i] = best
            caps[best] -= dem

    return list(open_set), assignment


def constructive_solution(facilities, customers, dist, method="greedy", randomness=0.0):
    """Build a feasible solution using a selectable constructive rule."""
    m = len(facilities)
    n = len(customers)
    if method == "greedy":
        return greedy_initial_solution(facilities, customers, dist)

    remaining = set(range(n))
    open_set = set()
    capacities = [facility["capacity"] for facility in facilities]
    assignment = [-1] * n

    while remaining:
        candidates = []
        for j in range(m):
            if j in open_set:
                continue
            feasible = [i for i in remaining if customers[i]["demand"] <= capacities[j]]
            if not feasible:
                continue
            covered = sum(customers[i]["demand"] for i in feasible)
            if method == "cost_benefit":
                score = covered / max(1.0, facilities[j]["fixed_cost"])
            elif method == "demand_weighted":
                score = sum(customers[i]["demand"] / max(1e-9, dist[i][j]) for i in feasible)
            elif method == "savings":
                nearest = sum(min(dist[i]) * customers[i]["demand"] for i in feasible)
                score = (nearest - sum(dist[i][j] * customers[i]["demand"] for i in feasible)) / max(1.0, facilities[j]["fixed_cost"])
            else:  # dual_based: reduced-cost proxy from demand pressure and fixed cost
                pressure = sum(customers[i]["demand"] * (1.0 + dist[i][j]) ** -1 for i in feasible)
                score = pressure / max(1.0, facilities[j]["fixed_cost"] / max(1, facilities[j]["capacity"]))
            candidates.append((score, j, feasible))
        if not candidates:
            return greedy_initial_solution(facilities, customers, dist)
        candidates.sort(reverse=True)
        pool_size = min(len(candidates), max(1, int(1 + randomness * len(candidates))))
        _, facility, _ = random.choice(candidates[:pool_size])
        open_set.add(facility)
        feasible = sorted(remaining, key=lambda i: (dist[i][facility], -customers[i]["demand"]))
        for i in feasible:
            if customers[i]["demand"] <= capacities[facility]:
                assignment[i] = facility
                capacities[facility] -= customers[i]["demand"]
                remaining.remove(i)

    return list(open_set), assignment


def greedy_repair_assignment(open_set, assignment, facilities, customers, dist):
    """Repair assignments after a customer-level neighborhood move."""
    m = len(facilities)
    capacities = [facilities[j]["capacity"] for j in range(m)]
    repaired = [-1] * len(customers)
    order = sorted(range(len(customers)), key=lambda i: customers[i]["demand"], reverse=True)
    for i in order:
        preferred = assignment[i] if 0 <= assignment[i] < m else None
        choices = list(open_set)
        choices.sort(key=lambda j: (j != preferred, dist[i][j]))
        for j in choices:
            if capacities[j] >= customers[i]["demand"]:
                repaired[i] = j
                capacities[j] -= customers[i]["demand"]
                break
        if repaired[i] == -1:
            return None
    return repaired


def objective(open_set, assignment, facilities, customers, dist):
    fixed = sum(facilities[j]["fixed_cost"] for j in set(open_set))
    assign_cost = 0.0
    for i, j in enumerate(assignment):
        assign_cost += dist[i][j] * customers[i]["demand"]
    return fixed + assign_cost


def reassign_to_nearest(open_set, facilities, customers, dist):
    m = len(facilities)
    n = len(customers)
    caps = [facilities[j]["capacity"] for j in range(m)]
    assignment = [-1] * n
    for i in sorted(range(n), key=lambda ii: customers[ii]["demand"], reverse=True):
        dem = customers[i]["demand"]
        best = None
        best_d = float("inf")
        for j in open_set:
            if caps[j] >= dem and dist[i][j] < best_d:
                best = j
                best_d = dist[i][j]
        if best is None:
            return None
        assignment[i] = best
        caps[best] -= dem
    return assignment


def neighborhood_move(open_set, facilities, customers, dist, move_type=None):
    m = len(facilities)
    open_set = set(open_set)
    move_type = move_type or random.choice(["open", "close", "swap", "double_swap", "shake"])
    if move_type == "open":
        closed = [j for j in range(m) if j not in open_set]
        if not closed:
            return list(open_set)
        j = random.choice(closed)
        open_set.add(j)
        assign = reassign_to_nearest(open_set, facilities, customers, dist)
        if assign is None:
            open_set.remove(j)
        return list(open_set)
    elif move_type == "close":
        if len(open_set) <= 1:
            return list(open_set)
        j = random.choice(list(open_set))
        open_set.remove(j)
        assign = reassign_to_nearest(open_set, facilities, customers, dist)
        if assign is None:
            open_set.add(j)
        return list(open_set)
    elif move_type == "swap":
        closed = [j for j in range(m) if j not in open_set]
        if not closed or len(open_set) == 0:
            return list(open_set)
        j_open = random.choice(list(open_set))
        j_closed = random.choice(closed)
        open_set.remove(j_open)
        open_set.add(j_closed)
        assign = reassign_to_nearest(open_set, facilities, customers, dist)
        if assign is None:
            open_set.remove(j_closed)
            open_set.add(j_open)
        return list(open_set)
    elif move_type == "double_swap":
        closed = [j for j in range(m) if j not in open_set]
        if len(open_set) < 2 or len(closed) < 2:
            return list(open_set)
        old = random.sample(list(open_set), 2)
        new = random.sample(closed, 2)
        candidate = (open_set - set(old)) | set(new)
        if reassign_to_nearest(candidate, facilities, customers, dist) is not None:
            return list(candidate)
        return list(open_set)
    else:  # shake: change several facilities to escape a local optimum
        closed = [j for j in range(m) if j not in open_set]
        swaps = min(random.randint(2, 4), len(open_set), len(closed))
        if swaps == 0:
            return list(open_set)
        old = random.sample(list(open_set), swaps)
        new = random.sample(closed, swaps)
        candidate = (open_set - set(old)) | set(new)
        if reassign_to_nearest(candidate, facilities, customers, dist) is not None:
            return list(candidate)
        return list(open_set)


def evaluate_solution(open_set, facilities, customers, dist):
    assignment = reassign_to_nearest(open_set, facilities, customers, dist)
    if assignment is None:
        return None
    return assignment, objective(open_set, assignment, facilities, customers, dist)


def random_candidate(open_set, facilities, customers, dist, neighborhoods):
    move = random.choice(neighborhoods)
    candidate_open = neighborhood_move(open_set, facilities, customers, dist, move)
    evaluated = evaluate_solution(candidate_open, facilities, customers, dist)
    if evaluated is None:
        return list(open_set), None, float("inf")
    assignment, value = evaluated
    return candidate_open, assignment, value


def solution_neighborhood_move(open_set, assignment, facilities, customers, dist, move_type):
    """Apply facility and customer-level neighborhoods to a full solution."""
    candidate_open = set(open_set)
    candidate_assignment = list(assignment)
    if move_type in {"open", "close", "swap", "double_swap", "shake"}:
        candidate_open = set(neighborhood_move(candidate_open, facilities, customers, dist, move_type))
        candidate_assignment = reassign_to_nearest(candidate_open, facilities, customers, dist)
    elif move_type == "relocate":
        customer = random.randrange(len(customers))
        alternatives = [j for j in candidate_open if j != candidate_assignment[customer]]
        if alternatives:
            candidate_assignment[customer] = min(alternatives, key=lambda j: dist[customer][j])
    else:  # reassignment_cluster: move a geographically related customer group
        anchor = random.randrange(len(customers))
        cluster = sorted(range(len(customers)), key=lambda i: dist[anchor][candidate_assignment[i]])[:max(2, len(customers) // 10)]
        for customer in cluster:
            alternatives = [j for j in candidate_open if j != candidate_assignment[customer]]
            if alternatives:
                candidate_assignment[customer] = min(alternatives, key=lambda j: dist[customer][j])
    if candidate_assignment is None:
        return list(open_set), None, float("inf")
    repaired = greedy_repair_assignment(candidate_open, candidate_assignment, facilities, customers, dist)
    if repaired is None:
        return list(open_set), None, float("inf")
    return list(candidate_open), repaired, objective(candidate_open, repaired, facilities, customers, dist)


def random_solution_candidate(solution, facilities, customers, dist, neighborhoods):
    return solution_neighborhood_move(
        solution[0], solution[1], facilities, customers, dist, random.choice(neighborhoods)
    )


def simulated_annealing(facilities, customers, dist, init_open, init_assignment, iters=5000, t0=1000.0, alpha=0.995, neighborhoods=None):
    neighborhoods = neighborhoods or ["open", "close", "swap", "double_swap", "shake"]
    current_open = list(init_open)
    current_assignment = list(init_assignment)
    current_obj = objective(current_open, current_assignment, facilities, customers, dist)
    best_open = list(current_open)
    best_assignment = list(current_assignment)
    best_obj = current_obj
    T = t0

    for k in range(iters):
        cand_open, cand_assignment, cand_obj = random_candidate(
            current_open, facilities, customers, dist, neighborhoods
        )
        if cand_assignment is None:
            continue
        delta = cand_obj - current_obj
        if delta < 0 or random.random() < math.exp(-delta / max(1e-9, T)):
            current_open = cand_open
            current_assignment = cand_assignment
            current_obj = cand_obj
            if current_obj < best_obj:
                best_open = list(current_open)
                best_assignment = list(current_assignment)
                best_obj = current_obj
        T *= alpha
    return best_open, best_assignment, best_obj


def hill_climbing(facilities, customers, dist, init_open, init_assignment, iters=5000, neighborhoods=None):
    neighborhoods = neighborhoods or ["open", "close", "swap"]
    current_open = list(init_open)
    current_assignment = list(init_assignment)
    current_obj = objective(current_open, current_assignment, facilities, customers, dist)
    for _ in range(iters):
        cand_open, cand_assignment, cand_obj = random_candidate(
            current_open, facilities, customers, dist, neighborhoods
        )
        if cand_assignment is not None and cand_obj < current_obj:
            current_open, current_assignment, current_obj = cand_open, cand_assignment, cand_obj
    return current_open, current_assignment, current_obj


def tabu_search(facilities, customers, dist, init_open, init_assignment, iters=5000, tenure=12, neighborhoods=None):
    neighborhoods = neighborhoods or ["open", "close", "swap", "double_swap"]
    current_open = list(init_open)
    current_assignment = list(init_assignment)
    current_obj = objective(current_open, current_assignment, facilities, customers, dist)
    best_open, best_assignment, best_obj = list(current_open), list(current_assignment), current_obj
    tabu = {}
    for iteration in range(iters):
        candidates = []
        for _ in range(min(20, max(4, len(facilities)))):
            candidate = random_candidate(current_open, facilities, customers, dist, neighborhoods)
            if candidate[1] is not None:
                candidates.append(candidate)
        if not candidates:
            continue
        allowed = [candidate for candidate in candidates
                   if tuple(sorted(candidate[0])) not in tabu or candidate[2] < best_obj]
        if not allowed:
            allowed = candidates
        current_open, current_assignment, current_obj = min(allowed, key=lambda item: item[2])
        tabu[tuple(sorted(current_open))] = iteration + tenure
        tabu = {key: expiry for key, expiry in tabu.items() if expiry > iteration}
        if current_obj < best_obj:
            best_open, best_assignment, best_obj = list(current_open), list(current_assignment), current_obj
    return best_open, best_assignment, best_obj


def iterated_local_search(facilities, customers, dist, init_open, init_assignment, iters=5000, neighborhoods=None):
    neighborhoods = neighborhoods or ["open", "close", "swap"]
    best = hill_climbing(facilities, customers, dist, init_open, init_assignment, max(1, iters // 5), neighborhoods)
    for _ in range(5):
        shaken = neighborhood_move(best[0], facilities, customers, dist, "shake")
        evaluated = evaluate_solution(shaken, facilities, customers, dist)
        if evaluated is None:
            continue
        candidate = hill_climbing(facilities, customers, dist, shaken, evaluated[0], max(1, iters // 5), neighborhoods)
        if candidate[2] < best[2]:
            best = candidate
    return best


def variable_neighborhood_search(facilities, customers, dist, init_open, init_assignment, iters=5000, neighborhoods=None):
    neighborhoods = neighborhoods or ["swap", "double_swap", "open", "close"]
    current = (list(init_open), list(init_assignment), objective(init_open, init_assignment, facilities, customers, dist))
    for move in neighborhoods:
        candidate_open = neighborhood_move(current[0], facilities, customers, dist, move)
        evaluated = evaluate_solution(candidate_open, facilities, customers, dist)
        if evaluated is None:
            continue
        candidate = hill_climbing(facilities, customers, dist, candidate_open, evaluated[0], max(1, iters // len(neighborhoods)), [move])
        if candidate[2] < current[2]:
            current = candidate
    return current


def solve_mip(facilities, customers, dist):
    if pulp is None:
        print("PuLP is not installed. Skipping MIP solve. Install pulp and re-run to enable MIP comparison.")
        return None, None, None
    m = len(facilities)
    n = len(customers)
    prob = pulp.LpProblem("CFLP", pulp.LpMinimize)
    y = [pulp.LpVariable(f"y_{j}", cat="Binary") for j in range(m)]
    x = [[pulp.LpVariable(f"x_{i}_{j}", cat="Binary") for j in range(m)] for i in range(n)]

    # objective
    prob += pulp.lpSum([facilities[j]["fixed_cost"] * y[j] for j in range(m)]) + pulp.lpSum(
        [dist[i][j] * customers[i]["demand"] * x[i][j] for i in range(n) for j in range(m)])

    # each customer assigned
    for i in range(n):
        prob += pulp.lpSum([x[i][j] for j in range(m)]) == 1
    # capacity
    for j in range(m):
        prob += pulp.lpSum([customers[i]["demand"] * x[i][j] for i in range(n)]) <= facilities[j]["capacity"] * y[j]
    # link x to y
    for i in range(n):
        for j in range(m):
            prob += x[i][j] <= y[j]

    solver = pulp.PULP_CBC_CMD(msg=False)
    prob.solve(solver)

    if pulp.LpStatus[prob.status] != "Optimal":
        print("MIP did not find optimal solution; status:", pulp.LpStatus[prob.status])
    open_set = [j for j in range(m) if pulp.value(y[j]) > 0.5]
    assignment = [None] * n
    for i in range(n):
        for j in range(m):
            if pulp.value(x[i][j]) > 0.5:
                assignment[i] = j
                break
    obj = pulp.value(prob.objective)
    return open_set, assignment, obj


def save_results(out_dir, name, open_set, assignment, obj):
    os.makedirs(out_dir, exist_ok=True)
    results = {
        "open_facilities": open_set,
        "assignment": assignment,
        "objective": obj,
    }
    path = os.path.join(out_dir, f"{name}_results.json")
    with open(path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"Saved results to {path}")


def visualize_and_save(out_dir, facilities, customers, assignment, open_set, filename="assignment.png"):
    if plt is None:
        print("matplotlib not installed. Skipping visualization. Install matplotlib to enable plotting.")
        return
    os.makedirs(out_dir, exist_ok=True)
    fig, ax = plt.subplots(figsize=(8, 8))

    # Prepare facility coords
    fx = [f["x"] for f in facilities]
    fy = [f["y"] for f in facilities]

    # Customer coords
    cx = [c["x"] for c in customers]
    cy = [c["y"] for c in customers]
    demands = [c["demand"] for c in customers]

    m = len(facilities)
    n = len(customers)

    # Color customers by assigned facility (use a categorical colormap)
    cmap = plt.get_cmap("tab20")
    colors = [cmap(assignment[i] % 20) if assignment[i] is not None else (0.5, 0.5, 0.5, 1.0) for i in range(n)]

    # Plot customers
    sizes = [max(10, d * 2) for d in demands]
    ax.scatter(cx, cy, c=colors, s=sizes, alpha=0.7, label="customers")

    # Plot facilities: open and closed
    open_mask = [j in open_set for j in range(m)]
    open_fx = [fx[j] for j in range(m) if open_mask[j]]
    open_fy = [fy[j] for j in range(m) if open_mask[j]]
    closed_fx = [fx[j] for j in range(m) if not open_mask[j]]
    closed_fy = [fy[j] for j in range(m) if not open_mask[j]]

    ax.scatter(closed_fx, closed_fy, c="#444444", marker="s", s=80, label="closed facilities")
    ax.scatter(open_fx, open_fy, c="#2ca02c", marker="*", s=180, edgecolors="black", label="open facilities")

    # Draw assignment lines (thin, faint)
    for i in range(n):
        j = assignment[i]
        if j is None:
            continue
        ax.plot([cx[i], fx[j]], [cy[i], fy[j]], c=colors[i], alpha=0.25, linewidth=0.7)

    ax.set_title("Capacitated Facility Location — Assignments")
    ax.legend(loc="upper right")
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.set_aspect("equal", adjustable="box")

    path = os.path.join(out_dir, filename)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"Saved visualization to {path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", type=str, default="test-run/data/sample_data.json")
    parser.add_argument("--out-dir", type=str, default="test-run/results")
    parser.add_argument("--iters", type=int, default=2000)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--method",
        choices=["sa", "hill_climbing", "tabu", "ils", "vns"],
        default="sa",
        help="Metaheuristic to run (default: sa)",
    )
    parser.add_argument(
        "--initializer",
        choices=["greedy", "cost_benefit", "demand_weighted", "savings", "dual_based"],
        default="greedy",
        help="Constructive heuristic for the initial solution (default: greedy)",
    )
    parser.add_argument(
        "--initializer-randomness",
        type=float,
        default=0.0,
        help="Randomness for constructive selection, from 0.0 to 1.0",
    )
    parser.add_argument(
        "--neighborhoods",
        default="open,close,swap,double_swap,shake",
        help="Comma-separated neighborhoods: open, close, swap, double_swap, shake",
    )
    parser.add_argument("--no-plot", action="store_true", help="Skip generating PNG visualization")
    args = parser.parse_args()

    random.seed(args.seed)
    if not 0.0 <= args.initializer_randomness <= 1.0:
        parser.error("--initializer-randomness must be between 0.0 and 1.0")
    if np is None:
        print("Warning: numpy not installed; running without numpy (slower/math)\nInstall numpy for better performance.")

    facilities, customers = load_data(args.data)
    dist = compute_distances(facilities, customers)

    print("Building initial solution...")
    init_open, init_assign = constructive_solution(
        facilities, customers, dist, method=args.initializer, randomness=args.initializer_randomness
    )
    init_obj = objective(init_open, init_assign, facilities, customers, dist)
    print(f"Initial objective ({args.initializer}): {init_obj:.2f}, open facilities: {len(init_open)}")

    neighborhoods = [name.strip() for name in args.neighborhoods.split(",") if name.strip()]
    valid_neighborhoods = {"open", "close", "swap", "double_swap", "shake"}
    unknown = set(neighborhoods) - valid_neighborhoods
    if not neighborhoods or unknown:
        parser.error("--neighborhoods must contain only open, close, swap, double_swap, shake")

    print(f"Running {args.method}...")
    methods = {
        "sa": lambda: simulated_annealing(
            facilities, customers, dist, init_open, init_assign,
            iters=args.iters, t0=1000.0, alpha=0.995, neighborhoods=neighborhoods,
        ),
        "hill_climbing": lambda: hill_climbing(
            facilities, customers, dist, init_open, init_assign,
            iters=args.iters, neighborhoods=neighborhoods,
        ),
        "tabu": lambda: tabu_search(
            facilities, customers, dist, init_open, init_assign,
            iters=args.iters, neighborhoods=neighborhoods,
        ),
        "ils": lambda: iterated_local_search(
            facilities, customers, dist, init_open, init_assign,
            iters=args.iters, neighborhoods=neighborhoods,
        ),
        "vns": lambda: variable_neighborhood_search(
            facilities, customers, dist, init_open, init_assign,
            iters=args.iters, neighborhoods=neighborhoods,
        ),
    }
    best_open, best_assign, best_obj = methods[args.method]()
    print(f"{args.method} best objective: {best_obj:.2f}, open facilities: {len(best_open)}")
    save_results(args.out_dir, args.method, best_open, best_assign, best_obj)

    if not args.no_plot:
        visualize_and_save(args.out_dir, facilities, customers, best_assign, best_open, filename=f"{args.method}_assignment.png")

    print("Solving MIP (exact)...")
    mip_open, mip_assign, mip_obj = solve_mip(facilities, customers, dist)
    if mip_obj is not None:
        print(f"MIP objective: {mip_obj:.2f}, open facilities: {len(mip_open)}")
        save_results(args.out_dir, "mip", mip_open, mip_assign, mip_obj)
        if not args.no_plot:
            visualize_and_save(args.out_dir, facilities, customers, mip_assign, mip_open, filename="mip_assignment.png")

    print(f"Final {args.method} solution (sample):")
    # print a compact representation
    print("Open facilities:", best_open)
    print("First 10 assignments (customer -> facility):")
    for i in range(min(10, len(customers))):
        print(f"customer {i} -> facility {best_assign[i]}")


if __name__ == "__main__":
    main()
